{{ range $k, $v := until (int .Values.agentReplicaCount) | default 5 }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: agent
  name: {{ $.Chart.Name }}-agent-{{ $v }}
spec:
  ports:
  - name: {{ $.Chart.Name }}-agent-{{ $v }}
    port: {{ $.Values.trogdorAgentPort }}
    protocol: TCP
    targetPort: {{ $.Values.trogdorAgentPort }}
  selector:
    app: {{ $.Chart.Name }}-agent
    statefulset.kubernetes.io/pod-name: {{ $.Chart.Name }}-agent-{{ $v }}
    release: {{ $.Release.Name }}
  type: NodePort
---
{{end}}
