apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-client-config
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  client_properties.json: '
{
  "sasl.mechanism": "PLAIN",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"{{ .Values.apiKey }}\" password=\"{{ .Values.apiSecret }}\";",
  "security.protocol": "SASL_SSL"
}
'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-topic-config
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  enterprise-topics.json: '
{
  "long_lived_task_duration_ms": {{ .Values.longLivedTaskMs }},
  "short_lived_task_duration_ms": {{ .Values.shortLivedTaskMs }},
  "topics": [
    {
      "name": "baseline_soak_big_topic_1000p",
      "partitions_count": 1000,
      "produce_mbs_throughput": 45,
      "consume_mbs_throughput": 120,
      "producer_count": 11,
      "consumer_count": 11
    },
    {
      "name": "baseline_soak_medium_topic_25p",
      "partitions_count": 25,
      "produce_mbs_throughput": 15,
      "consume_mbs_throughput": 30,
      "producer_count": 4,
      "consumer_count": 4,
      "idempotence_enabled": true
    },
    {
      "name": "baseline_soak_eos_topic_100p",
      "partitions_count": 100,
      "produce_mbs_throughput": 15,
      "consume_mbs_throughput": 30,
      "producer_count": 4,
      "consumer_count": 4,
      "transactions_enabled": true
    }
  ]
}
'
  one-large-topic.json: '
{
  "long_lived_task_duration_ms": {{ .Values.longLivedTaskMs }},
  "short_lived_task_duration_ms": {{ .Values.shortLivedTaskMs }},
  "topics": [
    {
      "name": "tenant_soak_topic_144p",
      "partitions_count": 144,
      "produce_mbs_throughput": 30,
      "consume_mbs_throughput": 60,
      "producer_count": 12,
      "consumer_count": 12
    }
  ]
}
'
  skewed-load-topics.json: '
{
  "long_lived_task_duration_ms": {{ .Values.longLivedTaskMs }},
  "short_lived_task_duration_ms": {{ .Values.shortLivedTaskMs }},
  "topics": [
    {
      "name": "tenant_soak_topic_4p",
      "partitions_count": 4,
      "produce_mbs_throughput": 15,
      "consume_mbs_throughput": 30,
      "producer_count": 4,
      "consumer_count": 4
    },
    {
      "name": "tenant_soak_low_bandwidth_topic_16p",
      "partitions_count": 16,
      "produce_mbs_throughput": 1,
      "consume_mbs_throughput": 2,
      "producer_count": 2,
      "consumer_count": 2,
      "idempotence_enabled": true
    }
  ]
}
'
