image:
  repository: confluent-docker.jfrog.io/confluentinc
  name: cc-soak-clients
  tag: 0.155.0-2.3.0-SNAPSHOT-11-gaf34942b4
  pullPolicy: IfNotPresent
trogdorCoordinatorPort: 9002
apiKey: "null"
apiSecret: "null"
bootstrapServer: "null"
topicConfigPath: "/mnt/config/topic/enterprise-topics.json"
performanceTestConfigPath: "/mnt/config/performance/performance_test.json"
shortLivedTaskMs: "900000"
shortLivedTaskRescheduleDelayMs: "0"
shortLivedTaskMinutes: "15" # sum of shortLivedTaskMs + shortLivedTaskRescheduleDelayMs; used to configure the frequency of the status reporter
longLivedTaskMs: "604800000"
logRetentionMs: "10800000"
debugLogs: "true"
agentCount: "6" # as much as agentReplicaCount in cc-trogdor-service
